name: Deploy
on:
  push:
    branches:
      - main
      - migrate-to-nextjs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: 'Install Git LFS'
        run: |
          curl -s https://git-lfs.github.com/install.sh | bash
      - name: Configure Git LFS
        run: |
          echo "*.pack filter=lfs diff=lfs merge=lfs -text" > .gitattributes
      - name: Set Identity
        run: |
          git config --global user.email "nmchavda99@gmail.com"
          git config --global user.name "Nirav Chavda"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Application
        run: npm run build
      - name: Deploy to GH Pages
        run: npm run deploy
